"""simplify discord-school-mapping db

Revision ID: 16ddf4ec175b
Revises: c1c207e7d88c
Create Date: 2023-03-05 09:38:36.785835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ddf4ec175b'
down_revision = 'c1c207e7d88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_to_school', 'subscription_name')
    op.drop_column('guild_to_school', 'notification_threshold')
    op.drop_column('guild_to_school', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_to_school', sa.Column('school_id', sa.VARCHAR(), nullable=False))
    op.add_column('guild_to_school', sa.Column('notification_threshold', sa.INTEGER(), nullable=True))
    op.add_column('guild_to_school', sa.Column('subscription_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
