"""add table for watching other urls

Revision ID: 3362bfdd5992
Revises: c1c207e7d88c
Create Date: 2023-03-01 20:59:15.556830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3362bfdd5992'
down_revision = 'c1c207e7d88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_urls',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('url_type', sa.String(), nullable=False),
    sa.Column('subscription_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id', 'url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_urls')
    # ### end Alembic commands ###
