"""fix keys and regen db

Revision ID: 7d481113f0cc
Revises: 16ddf4ec175b
Create Date: 2023-03-05 09:45:10.106161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d481113f0cc'
down_revision = '16ddf4ec175b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
