"""add table for watching other urls

Revision ID: a5394deb4f1f
Revises: c1c207e7d88c
Create Date: 2023-03-01 20:40:38.365246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5394deb4f1f'
down_revision = 'c1c207e7d88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_urls',
        sa.Column('guild_id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('url_type', sa.String(), nullable=False),
        sa.Column('subscription_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('guild_id', 'url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_urls')
    # ### end Alembic commands ###
