"""Initial migration

Revision ID: c1c207e7d88c
Revises: 
Create Date: 2023-03-01 20:34:41.637097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c207e7d88c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_to_school',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('notification_threshold', sa.Integer(), nullable=True),
    sa.Column('subscription_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'school_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_to_school')
    # ### end Alembic commands ###
