"""add tachannelid to watchedurls

Revision ID: c88220e2fcbf
Revises: a5394deb4f1f
Create Date: 2023-03-01 20:45:33.285452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88220e2fcbf'
down_revision = 'a5394deb4f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_urls', sa.Column('channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_urls', 'channel_id')
    # ### end Alembic commands ###
